blank_issues_enabled: false
contact_links:
  - name: 💬 Dúvidas e Discussões
    url: https://github.com/devbernardes/PORTFOLIO/discussions
    about: Por favor, use as Discussões para perguntas e conversas gerais sobre o projeto