blank_issues_enabled: false
contact_links:
  - name: Dúvidas e Discussões
    url: https://github.com/gabrieldeori/PORTFOLIO/discussions
    about: Por favor, use as Discussões para perguntas e conversas gerais